In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/df_final_limpio1206.csv')

<ipython-input-40-50b925ac9cbd>:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/df_final_limpio1206.csv')

In [ ]:
df_interbancario = df[df["TipoEnvio"] == "TRADICIONAL"]

In [ ]:
# Contar las apariciones de cada idCredito
conteo = df_interbancario['idCredito'].value_counts()

# Crear el nuevo DataFrame con 1/conteo
df_pesos = pd.DataFrame({
    'idCredito': conteo.index,
    'peso': 1 / conteo.values
})

In [ ]:
df_pesos

       idCredito      peso
0         641408  0.000219
1         621553  0.000221
2         658925  0.000223
3         642798  0.000226
4         494603  0.000228
...          ...       ...
51289     736370  1.000000
51290     734594  1.000000
51291     755315  1.000000
51292     740214  1.000000
51293     755604  1.000000

[51294 rows x 2 columns]

In [ ]:
df['idListaCobro'].nunique()

22952

In [ ]:
df.tail()

,idListaCobro,idCredito,consecutivoCobro,idBanco,montoExigible,montoCobrar,montoCobrado,fechaCobroBanco,idRespuestaBanco,fechaCreacionLista,horaCreacionLista,fechaEnvioCobro,idEmisora,Nombre,TipoEnvio
8608146,162271,741795,44299050,2,980.32,980.32,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608147,162271,741795,44299051,2,1633.86,1633.86,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608148,162271,742470,44299052,2,810.44,810.44,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608149,162271,742470,44299053,2,1350.74,1350.74,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608150,162271,742470,44299054,2,540.30,540.30,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL

In [ ]:
df_filtrado = df[
    (df['TipoEnvio'] == 'INTERBANCARIO') &
    (~df['Nombre'].str.contains('BANAMEX', case=False, na=False))
]

In [ ]:
df_filtrado['I'].value_counts()

idCredito
492866    27
625275    25
514071    25
587624    25
621352    25
          ..
644662     1
634678     1
632674     1
620017     1
646091     1
Name: count, Length: 8309, dtype: int64

In [ ]:
# Contar cuÃ¡ntas veces aparece cada idCredito
conteo = df_filtrado['idCredito'].value_counts()

# Crear un nuevo DataFrame con los pesos 1/conteo
df_pesos = pd.DataFrame({
    'idCredito': conteo.index,
    'peso': 1 / conteo.values
})

In [ ]:
df_pesos.describe()

           idCredito         peso
count    8309.000000  8309.000000
mean   541980.994584     0.411348
std    109438.913946     0.388101
min      4635.000000     0.037037
25%    501552.000000     0.071429
50%    576650.000000     0.250000
75%    619151.000000     1.000000
max    674592.000000     1.000000

In [ ]:
# Contar las apariciones de cada idCredito
conteo = df_interbancario['idCredito'].value_counts()

# Crear el nuevo DataFrame con 1/conteo
df_pesos = pd.DataFrame({
    'idCredito': conteo.index,
    'peso': 1 / conteo.values
})

In [ ]:
df_pesos.describe()

           idCredito         peso
count    8309.000000  8309.000000
mean   541980.994584     0.411348
std    109438.913946     0.388101
min      4635.000000     0.037037
25%    501552.000000     0.071429
50%    576650.000000     0.250000
75%    619151.000000     1.000000
max    674592.000000     1.000000

In [ ]:
df['TipoEnvio'].value_counts()

TipoEnvio
TRADICIONAL      6909155
EN LINEA         1432622
PARCIAL            86062
INTERBANCARIO      66849
CUENTA             63790
MATUTINO           49656
TARJETA               17
Name: count, dtype: int64

In [ ]:
df

,idListaCobro,idCredito,consecutivoCobro,idBanco,montoExigible,montoCobrar,montoCobrado,fechaCobroBanco,idRespuestaBanco,fechaCreacionLista,horaCreacionLista,fechaEnvioCobro,idEmisora,Nombre,TipoEnvio
0,101255,403369,27243365.0,72.0,707.20,707.20,0.0,NaN,DD00031,2022-10-10,09:42:00,10/10/2022,20.0,BBVA CUENTA MATUTINO,MATUTINO
1,101272,491208,27243582.0,2.0,675.06,675.06,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23.0,BBVA CLABE PARCIAL,PARCIAL
2,101272,500210,27243583.0,2.0,2274.30,2274.30,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23.0,BBVA CLABE PARCIAL,PARCIAL
3,101272,504708,27243580.0,2.0,6376.74,6376.74,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23.0,BBVA CLABE PARCIAL,PARCIAL
4,101272,506839,27243578.0,2.0,6478.11,6478.11,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23.0,BBVA CLABE PARCIAL,PARCIAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955798,139861,690791,35714869.0,12.0,596.64,596.64,0.0,NaN,4.0,2024-03-13,12:40:00,13/03/2024,6.0,BBVA TRADICIONAL REINTENTO,TRADICIONAL
955799,139861,690815,35714870.0,12.0,635.70,635.70,0.0,NaN,4.0,2024-03-13,12:40:00,13/03/2024,6.0,BBVA TRADICIONAL REINTENTO,TRADICIONAL
955800,139861,690842,35714871.0,12.0,1272.25,1272.25,0.0,NaN,4.0,2024-03-13,12:40:00,13/03/2024,6.0,BBVA TRADICIONAL REINTENTO,TRADICIONAL
955801,139861,690925,35714872.0,12.0,1272.25,1272.25,0.0,NaN,4.0,2024-03-13,12:40:00,13/03/2024,6.0,BBVA TRADICIONAL REINTENTO,TRADICIONAL
955802,139861,690930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['idRespuestaBanco'].value_counts()

idRespuestaBanco
4.0        8173188
0.0         245962
04           69610
4.0          41091
13.0         25861
26.0         13245
00            8312
2.0           7372
3.0           4764
8.0           3865
08            2636
0.0           2200
26            2163
1.0           1577
26.0          1489
30.0          1029
8.0            733
03             658
30             579
02             501
30.0           416
3.0            362
1.0            145
19.0           138
01              79
2.0             61
88.0            56
DD00031         18
10.0             8
84.0             7
88               6
19               6
18.0             5
10               4
88.0             2
42.0             2
53               1
Name: count, dtype: int64

In [ ]:
df

,idListaCobro,idCredito,consecutivoCobro,idBanco,montoExigible,montoCobrar,montoCobrado,fechaCobroBanco,idRespuestaBanco,fechaCreacionLista,horaCreacionLista,fechaEnvioCobro,idEmisora,Nombre,TipoEnvio
0,101255,403369,27243365,72,707.20,707.20,0.0,NaN,DD00031,2022-10-10,09:42:00,10/10/2022,20,BBVA CUENTA MATUTINO,MATUTINO
1,101272,491208,27243582,2,675.06,675.06,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23,BBVA CLABE PARCIAL,PARCIAL
2,101272,500210,27243583,2,2274.30,2274.30,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23,BBVA CLABE PARCIAL,PARCIAL
3,101272,504708,27243580,2,6376.74,6376.74,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23,BBVA CLABE PARCIAL,PARCIAL
4,101272,506839,27243578,2,6478.11,6478.11,0.0,NaN,04,2022-10-10,10:59:00,10/10/2022,23,BBVA CLABE PARCIAL,PARCIAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8608146,162271,741795,44299050,2,980.32,980.32,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608147,162271,741795,44299051,2,1633.86,1633.86,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608148,162271,742470,44299052,2,810.44,810.44,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608149,162271,742470,44299053,2,1350.74,1350.74,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL
8608150,162271,742470,44299054,2,540.30,540.30,0.0,NaN,4.0,2025-05-22,12:10:00,22/05/2025,5,BANAMEX TRADICIONAL REINTENTO,TRADICIONAL

In [ ]:
df['idListaCobro'].nunique()

22952

In [ ]:
filtro = df[df["TipoEnvio"] == "INTERBANCARIO"]

In [ ]:

filtro['TipoEnvio'].value_counts()

TipoEnvio
INTERBANCARIO    66849
Name: count, dtype: int64

In [ ]:
filtro['idListaCobro'].nunique()

88